Stock/Models/Pager.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Stock.Models
{
    public class Pager
    {
        public int TotalItems { get; set; }
        public int CurrentPage { get; set; }
        public int PageSize { get; set; }
        public int TotalPages { get; set; }
        public int StartPage { get; set; }
        public int EndPage { get; set; }

        public Pager()
        {

        }

        public Pager(int totalItems, int page, int pageSize = 20)
        {
            int totalPages = (int)Math.Ceiling((decimal)totalItems / (decimal)pageSize);
            int currentPage = page;

            int startPage = currentPage - 2;
            int endPage = currentPage + 1;

            if (startPage <= 0)
            {
                endPage = endPage - (startPage - 1);
                startPage = 1;
            }

            if (endPage > totalPages)
            {
                endPage = totalPages;
                if (endPage > 10)
                {
                    startPage = endPage - 4;
                }
            }

            TotalItems = totalItems;
            CurrentPage = currentPage;
            PageSize = pageSize;
            TotalPages = totalPages;
            StartPage = startPage;
            EndPage = endPage;
        }
    }
}

Stock/Controllers/MarketController.cs
using Microsoft.AspNetCore.Mvc;
using Stock.Data;
using Stock.Models;
using Stock.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
//using Stock.Views.Shared.Components.SearchBar;

namespace Stock.Controllers
{
    public class MarketController : Controller
    {
        private readonly IMarketService _marketService;

        public MarketController(IMarketService marketService)
        {
            _marketService = marketService;
        }

        public IActionResult Index(int pg = 1, string SearchText = "", string sortOrder = "")
        {    
            ViewBag.NameSortParm = String.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.DateSortParm = sortOrder == "Date" ? "date_desc" : "Date";
            ViewData["SortIconWalor"] = "";
            ViewData["SortIconZmiana"] = "";
            var stocks = _marketService.GetStocks();

            switch (sortOrder)
            {
                case "name_desc":
                    stocks = stocks.OrderByDescending(s => s.Stock).ToList();
                    ViewData["SortIconWalor"] = "fa fa-arrow-up";
                    break;
                case "Date":
                    stocks = stocks.OrderBy(s => s.Change).ToList();
                    ViewData["SortIconZmiana"] = "fa fa-arrow-down";
                    break;
                case "date_desc":
                    stocks = stocks.OrderByDescending(s => s.Change).ToList();
                    ViewData["SortIconZmiana"] = "fa fa-arrow-up";
                    break;
                default:
                    stocks = stocks.OrderBy(s => s.Stock).ToList();
                    ViewData["SortIconWalor"] = "fa fa-arrow-down";               
                    break;
            }
           
            /*if (SearchText != "" && SearchText != null)*/
            if (!String.IsNullOrEmpty(SearchText))
            {
                string SearchTextUpper = SearchText.ToUpper();
                var searchStocks = stocks.Where(p => p.Stock.Contains(SearchTextUpper)).ToList();
                return View(searchStocks);
            }

            const int pageSize = 20;
            if (pg < 1)
                pg = 1;

            int recsCount = stocks.Count();
            var pager = new Pager(recsCount, pg, pageSize); //SPager SearchPager = new SPager(recsCount, pg, pageSize) { Action = "Index", Controller = "Category", SearchText = SearchText };
            int recSkip = (pg - 1) * pageSize;
            var data = stocks.Skip(recSkip).Take(pager.PageSize).ToList(); //List<Category> retProducts = stocks.Skip(recSkip).Take(pageSize).ToList()
            this.ViewBag.Pager = pager; //ViewBag.SearchPager = SearchPager;
            return View(data); //return View(retProducts);
        }
    }
}

Stock/Controllers/ObservedController.cs
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Stock.Data;
using Stock.Models;
using Stock.Models.ViewModels;
using Stock.Services;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace Stock.Controllers
{
    public class ObservedController : Controller
    {
        private readonly ApplicationDbContext _db;
        private readonly IObservedService _service;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public ObservedController(ApplicationDbContext db, IObservedService service, SignInManager<ApplicationUser> signInManager)
        {
            _db = db;
            _service = service;
            _signInManager = signInManager;
        }

        public  IActionResult Index()
        {

            //if(User LogedIn)           
            if (User.Identity.IsAuthenticated)
            {
                var userStocks = _service.GetUserStocks();
                userStocks =  _db.Observed
                                  .Where(a => a.ApplicationUser.Id == HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value)
                                 .ToList();
                 
                return View(userStocks);
            }
            return RedirectToAction("Login", "Account");
        }

        //GET - Create
        [HttpGet]
        public IActionResult Create()
        {
            var TypeDropDown = _service.GetTypeDropDown();
            ViewBag.TypeDropDown = TypeDropDown;
            return View();
        }

        //POST - Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(ObservedVM model)
        {         
            if (ModelState.IsValid)
            {
                //_service.Create(model);
                var dbStock = _db.Market.FirstOrDefault(s => s.Id == model.MarketId);
                var observed = new Observed
                {
                    MarketId = model.MarketId,
                    NumberOfActions = model.NumberOfActions,
                    PurchasePrice = model.PurchasePrice,
                    Stock = dbStock.Stock,
                    Profit = model.NumberOfActions * (model.PurchasePrice - dbStock.Price),
                    ApplicationUserId = HttpContext.User.FindFirst(ClaimTypes.NameIdentifier).Value
                };

                _db.Observed.Add(observed);
                _db.SaveChanges();               
                return RedirectToAction("Index");
            }
            return View();
        }

        //GET - Delete
        [HttpGet]
        public IActionResult Delete(int? id)
        {
            if (id == null || id == 0)
            {
                return NoContent();
            }
            var obj = _db.Observed.Find(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //POST - Delete
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult DeletePost(int? id)
        {
            var obj = _service.GetById(id);
            if (obj == null)
            {
                return NotFound();
            }
            _db.Observed.Remove(obj);
            _db.SaveChanges();
            return RedirectToAction("Index");
        }

        //GET - Update
        [HttpGet]
        public IActionResult Update(int? id)
        {

            var TypeDropDown = _service.GetTypeDropDown();
            ViewBag.TypeDropDown = TypeDropDown;


            if (id == null || id == 0)
            {
                return NoContent();
            }
            var obj = _service.GetById(id);
            if (obj == null)
            {
                return NotFound();
            }
            return View(obj);
        }

        //POST - Update
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Update(ObservedVM model)
        {
            if (ModelState.IsValid)
            {
                _service.Update(model);
                return RedirectToAction("Index");
            }
            return View();
        }
    }
}

Stock/Views/Shared/Components/SearchBar/SearchBarViewComponent.cs
//using Microsoft.AspNetCore.Mvc;
//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Threading.Tasks;

//namespace Stock.Views.Shared.Components.SearchBar
//{
//    public class SearchBarViewComponent : ViewComponent
//    {
//        public SearchBarViewComponent()
//        {

//        }

//        public IViewComponentResult Invoke(SPager SearchPager)
//        {
//            return View("Default", SearchPager);
//        }
//    }
//}

Stock/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <title>@ViewData["Title"] - Stock</title>
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </head>
    <body>
        <header>
            <nav class="navbar navbar-inverse navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary box-shadow">           
                <div class="container">
                    
                    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>
                    <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                        <ul class="navbar-nav flex-grow-1">
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Market" asp-action="Index">Stock Market</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="" asp-controller="Observed" asp-action="Index">My Wallet</a>
                            </li>
                            <li class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                                <partial name="_LoginPartial" />
                            </li>
                        </ul>
                    </div>                    
                </div>
            </nav>
        </header>
        <div class="container-fluid nopadding">
            <main role="main" class="pb-3">
                @RenderBody()
            </main>
        </div>

        <footer class="border-top footer text-muted">
            <div class="container">
                &copy; 2021 - Stock - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
            </div>
        </footer>
        <script src="~/lib/jquery/dist/jquery.min.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
        @await RenderSectionAsync("Scripts", required: false)
    </body>
</html>

Stock/Views/Shared/_Pager.cshtml
@model Stock.Models.Pager

@if (Model.TotalPages > 0)
{
    <div class="col-8 p-0 justify-content-end">
        <ul class="pagination justify-content-end">

            @if (Model.CurrentPage > 1)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Market" asp-action="Index" asp-route-pg="1">First</a>
                </li>
                <li>
                    <a class="page-link" asp-controller="Market" asp-action="Index" asp-route-pg="@(Model.CurrentPage - 1)">Previous</a>
                </li>
            }


            @for (var pge = Model.StartPage; pge <= Model.EndPage; pge++)
            {
                <li class="page-item @(pge == Model.CurrentPage ? "active" : "")">
                    <a class="page-link" asp-controller="Market" asp-action="Index" asp-route-pg="@pge"> @pge</a>
                </li>
            }

            @if (Model.CurrentPage < Model.TotalPages)
            {
                <li class="page-item">
                    <a class="page-link" asp-controller="Market" asp-action="Index" asp-route-pg="@(Model.CurrentPage + 1)"> Next</a>
                </li>
                <li>
                    <a class="page-link" asp-controller="Market" asp-action="Index" asp-route-pg="@(Model.TotalPages)">Last</a>
                </li>
            }

        </ul>
    </div>
}

Stock/Views/Shared/_Search.cshtml
@model IEnumerable<Stock.Models.Market>

<div class="col-4 p-0 justify-content-end">
    <form asp-controller="Category" asp-action="Index">
        <span class="btn-group">
            <input class="form-control" type="text" name="SearchText" placeholder="Search Key" />
            <input class="p-1 ml-2 btn btn-primary" type="submit" value="Search" />
        </span>
    </form>
</div>